FIND_PATH( DBUS_INCLUDE_DIR dbus/dbus.h PATHS ${CMAKE_INCLUDE_PATH}/dbus-1.0 /usr/include/dbus-1.0)
FIND_PATH( DBUS_INCLUDE_LIB_DIR dbus/dbus-arch-deps.h PATHS ${CMAKE_LIBRARY_PATH}/dbus-1.0/include /usr/lib/dbus-1.0/include /usr/lib64/dbus-1.0/include)
FIND_PATH( DBUS_GLIB_INCLUDE_DIR dbus/dbus-glib.h PATHS ${CMAKE_INCLUDE_PATH})

FIND_LIBRARY(DBUS_LIBRARY NAME dbus-1 PATHS /lib)
FIND_LIBRARY(DBUS_GLIB_LIBRARY NAME dbus-glib PATHS /lib)

IF(NOT DBUS_GLIB_INCLUDE_DIR)
  MESSAGE(ERROR "Could not find dbus/dbus-glib.h")
ENDIF(NOT DBUS_GLIB_INCLUDE_DIR)

IF(NOT DBUS_GLIB_LIBRARY)
  MESSAGE(ERROR "Could not find lib dbus-glib-1")
ENDIF(NOT DBUS_GLIB_LIBRARY)

IF( DBUS_INCLUDE_DIR AND DBUS_INCLUDE_LIB_DIR AND DBUS_GLIB_INCLUDE_DIR AND DBUS_LIBRARY AND DBUS_GLIB_LIBRARY )
SET( DBUS_FOUND TRUE )
ENDIF( DBUS_INCLUDE_DIR AND DBUS_INCLUDE_LIB_DIR AND DBUS_GLIB_INCLUDE_DIR AND DBUS_LIBRARY AND DBUS_GLIB_LIBRARY )

IF( DBUS_INCLUDE_DIR AND DBUS_INCLUDE_LIB_DIR AND DBUS_GLIB_INCLUDE_DIR)
SET( DBUS_INCLUDES ${DBUS_INCLUDE_DIR} ${DBUS_INCLUDE_LIB_DIR} ${DBUS_GLIB_INCLUDE_DIR})
ENDIF( DBUS_INCLUDE_DIR AND DBUS_INCLUDE_LIB_DIR AND DBUS_GLIB_INCLUDE_DIR)

IF( DBUS_FOUND )
    MESSAGE( STATUS "Found dbus: ${DBUS_LIBRARY}" )
    ELSE( DBUS_FOUND )
    IF( DBUS_FIND_REQUIRED )
    	MESSAGE( FATAL_ERROR "Could not find dbus" )
    ENDIF( DBUS_FIND_REQUIRED )
ENDIF( DBUS_FOUND )


